---
deployment:
  tasks:
    # 1. Copy Frontend Build
    - /bin/cp -R build/* /home/skillsak/gatlafoundation.org/
    
    # 2. Copy Backend API
    - /bin/cp -R api /home/skillsak/gatlafoundation.org/
    
    # 3. Set Permissions
    - /bin/mkdir -p /home/skillsak/gatlafoundation.org/uploads
    - /bin/chmod -R 755 /home/skillsak/gatlafoundation.org/api
    - /bin/chmod -R 755 /home/skillsak/gatlafoundation.org/uploads